language: haskell

ghc:
  - 7.10

before_install:
  - sudo apt-get install msgpack-python

install:
  # TravisCI currently uses Ubuntu 12.04 which doesn't have a ruby-msgpack package.
  - gem install ffi msgpack
  - cabal install --only-dependencies --enable-tests --enable-shared

script:
  - cabal configure --enable-tests --enable-shared
  - cabal build

  # Cabal 1.22 puts the library .so files into dist/build.
  # In older cabals, it "magically" worked, see:
  #   https://github.com/haskell/cabal/issues/2330#issuecomment-69201669
  - LD_LIBRARY_PATH=dist/build python test.py
  - LD_LIBRARY_PATH=dist/build ruby test.rb
